apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "id-gen-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "id-gen-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "id-gen-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "id-gen-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "id-gen-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: "{{ .Release.Name }}-config"
          env:
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: rc-secret
                  key: DB_PASSWORD
            - name: spring.flyway.password
              valueFrom:
                secretKeyRef:
                  name: rc-secret
                  key: DB_PASSWORD
            - name: egov.mdms.provider
              value: {{ .Values.envVars.egov_mdms_provider | quote}}
            - name: spring.datasource.url
              value: {{ .Values.envVars.spring_datasource_url | quote}}
            - name: spring.flyway.url
              value: {{ .Values.envVars.spring_flyway_url | quote}}
            - name: spring.flyway.baseline-on-migrate
              value: {{ .Values.envVars.spring_flyway_baseline_on_migrate | quote}}
            - name: autocreate.new.seq
              value: {{ .Values.envVars.autocreate_new_seq | quote}}
            - name: idformat.from.mdms
              value: {{ .Values.envVars.idformat_from_mdms | quote}}
            - name: server.port
              value: {{ .Values.envVars.server_port | quote}}
            - name: management.endpoints.web.base-path
              value: {{ .Values.envVars.management_endpoints_web_base_path | quote}}
            - name: server.servlet.context-path
              value: {{ .Values.envVars.server_servlet_context_path | quote}}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            failureThreshold: 20
            periodSeconds: 30
            timeoutSeconds: 10
            initialDelaySeconds: 30
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
